### ISSUE TITLE
Ran into bug: Could not read npm version.

### ISSUE THREAD

**Issue by toddbluhm** [mariocasciaro/npm-workspace#27]
After upgrading to the new v5 version I ran into this log message on my first `npm-workspace install` on a top level folder (so subfolder repos to install).

`Could not read npm version. Is npm in your path? TypeError: Object #<Object> has no method 'execSync'`

node: 0.10.28
npm: 2.11.2
I was running this command as root

**Comment by i-e-b** [comment]
Does the install still happen correctly? New checks were added in 0.5.0 to try to maintain compatibility between npm 2.x and 3.x

**Comment by toddbluhm** [comment]
I was running it on npm-workspace 0.5.0. I just upgraded to the latest 0.6.1 and its still happening. I also updated node and npm, but still no luck

npm-workspace: 0.6.1
node: 0.10.40
npm: 2.14.8

**Comment by i-e-b** [comment]
Sure, but that error comes from https://github.com/mariocasciaro/npm-workspace/blob/master/lib/npm-workspace.js#L36 (due to using node 0.10.40)

The install process _should_ still complete despite the warning message. Is your install completing, is the process terminating, or are you seeing further errors?

**Comment by toddbluhm** [comment]
The install is completing and things seem to be working just fine. I was just reporting the weird error.

**Comment by i-e-b** [comment]
Ok, thanks. There is a PR open that will remove this error.

**Comment by mariocasciaro** [comment]
PR merged
